name: Release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    container: node:lts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Compile
        run: yarn build
      - name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
